version: '3.8'
services:
  web:
    build: .
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - db
    command: python3 manage.py runserver 0.0.0.0:8001
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devsearch
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    container_name: postgres_devsearch_ky